services:
  - type: web
    name: order-backend
    env: ruby
    rootDir: order_backend
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: order-db
          property: connectionString
  - type: pgsql
    name: order-db
    databaseName: order_app_production
    user: order_app